# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eureka < Formula
  desc ""
  homepage ""
  version "4.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mimoo/eureka/releases/download/v4.1.0/eureka_4.1.0_Darwin_x86_64.tar.gz"
    sha256 "06ab0647f78ddd3e92a0d968d5f4d81550ae262da38396be636215bc2a05f061"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/mimoo/eureka/releases/download/v4.1.0/eureka_4.1.0_Linux_x86_64.tar.gz"
    sha256 "cbe84d25c04f94dde26b3ff1265255975dbccca269651e025bea613a579ccfc8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/mimoo/eureka/releases/download/v4.1.0/eureka_4.1.0_Linux_arm64.tar.gz"
    sha256 "0128dd47acc736c947d554b95df502335bfb707dcc5f59bd21b91756a7973ff6"
  end

  def install
    bin.install "eureka"
  end
end
